params:
  m: 2000
  rho: 1.225
  C_d: 0.4
  Af: 1.6
  V_wind: 10
  a: 1.1
  b: 1.2
  l: 2.3
  tf: 1.58
  tr: 1.58
  w: 1.58
  Izz_v: 6060.373333333333
  max_torque: 450
  max_power: 225000
  C_x: 50000
  C_y: 40000
  R_f: 0.334
  R_r: 0.334
  tire_m_f: 12
  tire_m_r: 12
  Iyy_w_f: 2.004
  Iyy_w_r: 2.004
  slip_min: -0.1
  no_drive_wheels: 2
  g: 9.8
  h: 0.25
  min_vel: 0
  max_vel: 45
  Kp: 500
  Ki: 10
  Kd: 10
